#! /usr/bin/env node

const execute = async () => {

  e("👩🏿‍✈️", "woman pilot, dark skin tone");
  e("👩🏼‍🎤", "woman singer, medium-ligh skin tone");
  e("👩🏿‍🎤", "woman singer, dark skin tone ");
  e("🦸🏻‍♀", "woman superhero, light skin tone");
  e("🧙🏽‍♀", "woman mage, medium skin tone");
  e("👨‍👨‍👧‍👧", "family: man,man, girl, girl");
  e("👨‍👩‍👧‍👦", "family: man, woman, girl, boy");
  e("👳‍♀️", "woman wearing turban");
  e("👳‍♀", "woman wearing turban");
  e("🦲", "Bald");
  e("🦳", "White hair");
  e("🦱", "Curly hair");
  e("🦰", "Red hair");
  e("🏻", "light skin tone");
  e("🏼", "medium-light skin tone");
  e("🏽", "medium skin tone");
  e("🏾", "medium-dark skin tone");
  e("🏿", "dark skin tone");
  e("🧞‍♀", "I Dream of Jeannie");
  e("🧛🏻‍♂", "Dracula light skin female");
  e("㊙️", "secret1");
  e("㊙", "secret2");
  e("✡️", "david1");
  e("✡", "david2");
  e("☠️", "skull & bones1");
  e("☠", "skull & bones2");
  e("🕹️", "joystick1");
  e("🕹", "joystick2");
  e("🇻🇦", "flag Vatikan");
  e("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "flag wales");
  e("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "flag scotland");
  e("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "flag england");
  e("🇦🇹", "flag austria");
  e("🇽🇰", "flag cosovo");
  e("🇱🇮", "Liechtenstein");
  e("🇺🇳", "United Nations");
  e("🇺🇸", "United States");
  e("🇩🇬", "Diego Garcia");
  e("👣", "footprints");
  e("💯", "hundred points");
  e("💤", "zzz");
  e("🙈", "see no evil monkey");
  e("🙉", "hear no evil monkey");
  e("🙊", "speak no evil monkey");
  e("🌊", "water wave");
  e("☄️", "comet");
  e("🔗", "chain");
  e("🔨", "hammer");
  e("🗺️", "world map");
  e("🌍", "Europe");
  e("🌎", "Americas");
  e("🌏", "Asia");
  e("🌐", "globe");
  e("🗾", "Japan");
  e("🗼", "tokyo tower");
  e("🗽", "Liberty");
  e("🏣", "japanese post office");
  e("🏤", "post office");
  e("🗻", "mount fuji");
  e("🏪", "shop24");
  e("🚅", "bullet train");
  e("🕋", "kaaba");
  e("⛩", "shinto");
  e("🕍", "synagoge");
  e("🛕", "hindu temple");
  e("🕌", "mosque");
  e("⛪", "church");
  e("🏩", "love hotel");
  e("🈚", "free of charge")
  e("♏", "scorpion");
  e("♈", "widder");
  e("🪂", "parachute");
  e("🚀", "rocket");
  e("🛺", "tuktuk");
  e("🛹", "skateboard");
  e("🛸", "flying saucer");
  e("🍃", "leaf fluttering in wind");
  e("🍂", "fallen leaf");
  e("🍁", "maple leaf");
  e("☘", "shamrock");
  e("🌿", "herb");
  e("🌾", "rice");
  e("🌵", "cactus");
  e("🪴", "potted plant");
  e("🌸", "cherry blossom");
  e("🕸", "spider web");
  e("🐞", "lady beetle");
  e("🦭", "seal");
  e("🪢", "knot");
  e("🪀", "jojo");
  e("🖼", "framed picture");
  e("🍺", "beer mug");
  e("🥓", "bacon");
  e("🎮", "video game");
  e("🎴", "flower playing card");
};

const e = (e, m) => {
  //console.log(e, ethers.utils.toUtf8Bytes(e).replace(/(\r\n|\n|\r)/gm, ""), m);
  console.log(e, "|", ethers.utils.toUtf8Bytes(e), ":", m);
};

const ethers = require('ethers');

execute();
